services:
  app:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    command: sh -c "pip install -r requirements.txt && python main.py"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data

volumes:
  postgres_orders_data: